```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### BIOL 812 Final Project
# Evolutionary Relationships of the Coronaviruses

#### Authors: Casmey, K.\*\, Yoo, G.\*\, Ermakova, G.\*\, and Lounder, H\*\.
\*\ All authors contributed to the conceptualization, formal analysis, methodology, project administration, visualization, and writing.

##### Project Repository: [https://github.com/gyoo1/BIOL812_FinalProject](https://github.com/gyoo1/BIOL812_FinalProject)

### Background 
In December 2019, numerous cases of an unknown respiratory virus were reported in the city of Wuhan, China. A coronavirus, SARS-CoV-2 was identified as the causative agent for the illness. This virus is closely related to SARS-CoV which was responsible for the SARS outbreak of 2002-2004. A pandemic was declared in March 2020 due to the SARS-CoV-2 virus. Other coronaviruses, NL63, 229E, HKU1, and OC43, cause common colds in humans. Coronaviruses are also present in various animals. We seek to address the following questions. 

### Questions
1. What is the evolutionary relationship among the human coronavirus strains?

2. What is the evolutionary relationship between the human and animal coronavirus strains?

3. To design a therapy (i.e., mRNA vaccine), which sequence would you target in hopes to carry over immunity between other strains as well? 


### Methods
#### Samples
Number | Accession | Abbreviation | Genome | Organism | Length (bp)
------ | --------- | ------------ | ------ | -------- | -----------
1 | OL855841.1 | WtD-SARS-CoV2 | Severe acute respiratory syndrome Coronavirus-2 | White-tailed deer (*Odocoileus virginianus*) | 29831
2 | ON078487.1 | SARS-CoV2-Omicron | Omicron variant; Severe acute respiratory syndrome Coronavirus-2 | Human | 29698
3 | BS001349.1 | SARS-CoV2-BS | Delta variant; Severe acute respiratory syndrome Coronavirus-2 | Human | 29809
4 | NC_045512.2 | SARS-CoV2-NC | Alpha variant; Severe acute respiratory syndrome Coronavirus-2 | Human | 29903
5 | DQ022305.2 | Bat-SARS-CoV | Severe acute respiratory syndrome Coronavirus HKU3-1 | Chinese horseshoe bat (*Rhinolophus sinicus*) | 29728
6 | NC_004718.3 | SARS-CoV | Severe acute respiratory syndrome Coronavirus | Human | 29751
7 | NC_019843.3 | MERS-CoV | Middle East respiratory syndrome Coronavirus | Human | 30119
8 | NC_006577.2 | HCoV-HKU1 | Human Coronavirus HKU1 | Human | 29926
9 | NC_006213.1 | HCoV-OC43 | Human Coronavirus OC43 | Human | 30741
10 | MG518518.1 | WD-BCoV | Water deer Bovine Coronavirus | Water deer (*Hydropotes inermis*) | 31034
11 | FJ425189.1 | SD-CoV | Sambar deer Coronavirus | Sambar deer (*Rusa unicolor*) | 30997
12 | FJ425187.1 | WtD-CoV | White-tailed deer Coronavirus | White-tailed deer (*Odocoileus virginianus*) | 31020
13 | NC_005831.2 | HCoV-NL63 | Human Coronavirus NL63 | Human | 27553
14 | NC_002645.1 | HCoV-229E | Human Coronavirus 229E | Human | 27317

We used whole-genome sequences of 14 coronavirus strains, all publically available from GenBank. Our sample includes 4 strains responsible for the current COVID-19 pandemic (SARS-CoV-2), with the alpha, delta, and omicron strains represented, along with a SARS-CoV-2 strain from white-tailed deer. We also include 2 strains of the SARS-CoV virus, responsible for the SARS epidemic. We use SARS strains from human and Chinese horeshoe bats. We also include other coronaviruses, 


## Results and Interpretations